name: Pipeline Test

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install sqlalchemy
        
    - name: Test and Run
      run: chmod +x project/tests.sh
